// <auto-generated />
using FinalProject_ContemporaryProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_ContemporaryProgramming.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20260407140807_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_ContemporaryProgramming.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HobbiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Engaging with written content for pleasure and knowledge.",
                            HobbiesId = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Preparing food for enjoyment and sustenance.",
                            HobbiesId = 2,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Exploring new places and cultures for leisure.",
                            HobbiesId = 3,
                            Name = "Traveling"
                        });
                });

            modelBuilder.Entity("FinalProject_ContemporaryProgramming.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<string>("TeamMemberBirthdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamMemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMemberId = 1,
                            TeamMemberBirthdate = "2005-1-1",
                            TeamMemberName = "Aneesh Palande",
                            TeamMemberProgram = "Information Technology",
                            TeamMemberYear = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 2,
                            TeamMemberBirthdate = "2005-1-1",
                            TeamMemberName = "Alex Lauffenberger",
                            TeamMemberProgram = "CyberSecurity",
                            TeamMemberYear = "Pre-Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
